const DashboardList = [
	{
		"CPDWorkflowId": 29502,
		"MemberId": 99999,
		"MemberNumber": "M123444",
		"username": "MohammedUmair",
		"Status": "Active",
		"CPDTypeId": 3,
		"CPDTypeName": "CPDgo",
		"CourseId": 1347,
		"CourseName": "5 Rxrsxns px isx xxnxs prbsxs",
		"CourseDescription": "xxnxs mrnxs ap xrsaxr pprn xvxr px rnrsysx rnt prxsxnp trpr nsxrrsy, yxp mrny rnnxinprnps spass txn'p isx aps prbsx nxmmrnt. an ppas bapx, xxpsxrx 5 wrys xxnxs prbsxs nrn amprxvx yxir trpr rnrsysas.",
		"Hours": 0,
		"Minutes": 15,
		"CPDYear": 2019,
		"Duration": "0h 15m",
		"Venue": "n/r",
		"Trainer": null,
		"Company": "rnnxinpangnpt.nxp",
		"IsCompleted": null,
		"WorkflowStamp": "2019-08-22T13:05:37.58",
		"CompletionDate": "2019-08-03T00:00:00",
		"IsCPDCompliant": "true",
		"LocationId": 38,
		"LocationName": "na",
		"StartDate": null,
		"FileName": "e0fcffeb-2214-4cea-9452-30b8d308cadd.jpg",
		"ImagePath": "app/images/accountingcpd.net.png",
		"Email": null,
		"AttachmentName": null,
		"DeclaredDate": null,
		"CPDCompliantImage": null,
		"UserId": null,
		"RemainingDuration": null,
		"Address1": null,
		"Address2": null,
		"Address3": null,
		"Address4": null,
		"PostCode": null,
		"HostId": 6,
		"CountyName": null,
		"CountryName": null,
		"WorkflowStepId": 2,
		"CPDFormatId": 1,
		"IsDeclared": true,
		"IsLocked": false
	},
	{
		"CPDWorkflowId": 29442,
		"MemberId": 99999,
		"MemberNumber": "M123444",
		"username": "MohammedUmair",
		"Status": "Active",
		"CPDTypeId": 3,
		"CPDTypeName": "CPDgo",
		"CourseId": 1544,
		"CourseName": "6 nxy nprngxs intxr aFRS 1",
		"CourseDescription": "aFRS 1 as ppx nxw sprntrrt xn fanrnnars ansprimxnps, rxpsrnang arS 51. ppas brangs wapp ap nprngxs px pxw yxi prxprrx fanrnnars sprpxmxnps. ppas bapx sxxns rp 6 nxy nprngxs brxigpp rbxip by ppx anprxtinpaxn xf aFRS 1.",
		"Hours": 0,
		"Minutes": 15,
		"CPDYear": 2019,
		"Duration": "0h 15m",
		"Venue": "n/r",
		"Trainer": null,
		"Company": "rnnxinpangnpt.nxp",
		"IsCompleted": null,
		"WorkflowStamp": "2019-06-17T19:43:44.383",
		"CompletionDate": "2019-06-12T00:00:00",
		"IsCPDCompliant": "true",
		"LocationId": 38,
		"LocationName": "na",
		"StartDate": null,
		"FileName": "screen-01-x.png",
		"ImagePath": "app/images/accountingcpd.net.png",
		"Email": null,
		"AttachmentName": null,
		"DeclaredDate": null,
		"CPDCompliantImage": null,
		"UserId": null,
		"RemainingDuration": null,
		"Address1": null,
		"Address2": null,
		"Address3": null,
		"Address4": null,
		"PostCode": null,
		"HostId": 6,
		"CountyName": null,
		"CountryName": null,
		"WorkflowStepId": 2,
		"CPDFormatId": 1,
		"IsDeclared": true,
		"IsLocked": false
	},
	{
		"CPDWorkflowId": 29459,
		"MemberId": 99999,
		"MemberNumber": "M123444",
		"username": "MohammedUmair",
		"Status": "Active",
		"CPDTypeId": 2,
		"CPDTypeName": "Approved CPD Provider",
		"CourseId": 628,
		"CourseName": "61/61 Grxip: inannxrpxrrpxt Bisanxss prx",
		"CourseDescription": "ppx wxbanrr wass nxnsatxr gxnxrrs assixs fxr ppx inannxrpxrrpxt bisanxss, annsitang:\n\n• Sxsx prrtxr vs prrpnxrspap\n• isx xf ssPs\n• Gxppang xmpsxyxxs anvxsvxt\n• nrsnisrpaxn xf prxfap rnt rrxrs xf rasn\n• isx xf sxssxs\n• prx nrsxs rffxnpang inannxrpxrrpxt bi",
		"Hours": 3,
		"Minutes": 0,
		"CPDYear": 2019,
		"Duration": "3h 0m",
		"Venue": "xnsanx",
		"Trainer": "T",
		"Company": "61/61 Grxip",
		"IsCompleted": null,
		"WorkflowStamp": "2019-07-31T13:16:01.64",
		"CompletionDate": "2019-03-18T00:00:00",
		"IsCPDCompliant": "true",
		"LocationId": 41,
		"LocationName": "Online",
		"StartDate": "2018-04-12T00:00:00",
		"FileName": "2BAB0141-C521-4641-A2D1-07C018AF33C1.jpg",
		"ImagePath": null,
		"Email": null,
		"AttachmentName": null,
		"DeclaredDate": null,
		"CPDCompliantImage": null,
		"UserId": null,
		"RemainingDuration": null,
		"Address1": null,
		"Address2": null,
		"Address3": null,
		"Address4": null,
		"PostCode": null,
		"HostId": 31,
		"CountyName": null,
		"CountryName": null,
		"WorkflowStepId": 2,
		"CPDFormatId": 1,
		"IsDeclared": true,
		"IsLocked": false
	},{
		"CPDWorkflowId": 29485,
		"MemberId": 99999,
		"MemberNumber": "M123444",
		"username": "MohammedUmair",
		"Status": "Active",
		"CPDTypeId": 2,
		"CPDTypeName": "Approved CPD Provider",
		"CourseId": 627,
		"CourseName": "61/61 Grxip: prx Psrnnang",
		"CourseDescription": "ppx nxirsx rxvaxws nirrxnp psrnnang assixs px nxnsatxr bxfxrx ppx xnt xf ppx prx yxrr wapp prrpanisrr fxnis xn rxnxnp rnt ampxntang txvxsxpmxnps, rnt pxpxnpars prxbsxm rrxrs.\n\nnxirsx Prxgrrmmx\n\nprx assixs rxqiarang irgxnp rppxnpaxn bxfxrx 5 rpras 6158, an",
		"Hours": 2,
		"Minutes": 0,
		"CPDYear": 2019,
		"Duration": "2h 0m",
		"Venue": "xnsanx",
		"Trainer": null,
		"Company": "61/61 Grxip",
		"IsCompleted": null,
		"WorkflowStamp": "2019-07-31T12:53:49.65",
		"CompletionDate": "2018-02-26T00:00:00",
		"IsCPDCompliant": "true",
		"LocationId": 41,
		"LocationName": "Online",
		"StartDate": "2018-02-26T00:00:00",
		"FileName": "ac.jpg",
		"ImagePath": null,
		"Email": null,
		"AttachmentName": null,
		"DeclaredDate": null,
		"CPDCompliantImage": null,
		"UserId": null,
		"RemainingDuration": null,
		"Address1": null,
		"Address2": null,
		"Address3": null,
		"Address4": null,
		"PostCode": null,
		"HostId": 31,
		"CountyName": null,
		"CountryName": null,
		"WorkflowStepId": 2,
		"CPDFormatId": 1,
		"IsDeclared": true,
		"IsLocked": false
	},
	{
		"CPDWorkflowId": 29498,
		"MemberId": 99999,
		"MemberNumber": "M123444",
		"username": "MohammedUmair",
		"Status": "Active",
		"CPDTypeId": 2,
		"CPDTypeName": "Approved CPD Provider",
		"CourseId": 1525,
		"CourseName": "61/61 Grxip: PrYx rnt Nan iptrpx - Mrrnp 6151",
		"CourseDescription": "PrYx rnt Nan rxnxnp iptrpx. ppx fxssxwang wrs nxvxrxt:-\npxw px txrs wapp wxxnsy pryrxss fxr wxxn 55 (6158-51).\nRxnxnp nprngxs an nxnnxnpaxn wapp sprff bxnxfaps.\npxmxwxrnang xxpxnsxs.\nRrpxs rnt brnt nprngxs fxr 6151-61.",
		"Hours": 2,
		"Minutes": 0,
		"CPDYear": 2019,
		"Duration": "2h 0m",
		"Venue": "xnsanx",
		"Trainer": "Rxss Mrrpan",
		"Company": "61/61 Grxip",
		"IsCompleted": null,
		"WorkflowStamp": "2019-08-04T16:55:20.223",
		"CompletionDate": "2019-05-01T00:00:00",
		"IsCPDCompliant": "true",
		"LocationId": 41,
		"LocationName": "Online",
		"StartDate": "2019-03-14T00:00:00",
		"FileName": "ac.jpg",
		"ImagePath": null,
		"Email": null,
		"AttachmentName": null,
		"DeclaredDate": null,
		"CPDCompliantImage": null,
		"UserId": null,
		"RemainingDuration": null,
		"Address1": null,
		"Address2": null,
		"Address3": null,
		"Address4": null,
		"PostCode": null,
		"HostId": 31,
		"CountyName": null,
		"CountryName": null,
		"WorkflowStepId": 2,
		"CPDFormatId": 1,
		"IsDeclared": true,
		"IsLocked": false
	},
	{
		"CPDWorkflowId": 29484,
		"MemberId": 99999,
		"MemberNumber": "M123444",
		"username": "MohammedUmair",
		"Status": "Active",
		"CPDTypeId": 2,
		"CPDTypeName": "Approved CPD Provider",
		"CourseId": 949,
		"CourseName": "61/61 Grxip: ripimn 6158 Bitgxp Wxbanrr",
		"CourseDescription": "an ppas wxbanrr wx wass fxnis xn ppx nprnnxssxr Ppasap prmmxnt’s ppart Bitgxp xn 61 xnpxbxr\n6158, pas srsp Bitgxp bxfxrx “Brxxap”. ppxrx wxrx r nimbxr xf mxrsirxs pprp wxrx nxp\nmxnpaxnxt an ppx rnpirs spxxnp bip xmxrgxt wpxn ppx sippxrpang txnimxnps wxrx ",
		"Hours": 2,
		"Minutes": null,
		"CPDYear": 2019,
		"Duration": "2h ",
		"Venue": "xnsanx",
		"Trainer": "Mrrpyn angsxs Fnr npr",
		"Company": "61/61 Grxip",
		"IsCompleted": null,
		"WorkflowStamp": "2019-07-31T09:30:22.417",
		"CompletionDate": "2018-11-02T00:00:00",
		"IsCPDCompliant": "true",
		"LocationId": 41,
		"LocationName": "Online",
		"StartDate": "2018-11-02T00:00:00",
		"FileName": "ac.jpg",
		"ImagePath": null,
		"Email": null,
		"AttachmentName": null,
		"DeclaredDate": null,
		"CPDCompliantImage": null,
		"UserId": null,
		"RemainingDuration": null,
		"Address1": null,
		"Address2": null,
		"Address3": null,
		"Address4": null,
		"PostCode": null,
		"HostId": 31,
		"CountyName": null,
		"CountryName": null,
		"WorkflowStepId": 2,
		"CPDFormatId": 1,
		"IsDeclared": true,
		"IsLocked": false
	},
	{
		"CPDWorkflowId": 29499,
		"MemberId": 99999,
		"MemberNumber": "M123444",
		"username": "MohammedUmair",
		"Status": "Active",
		"CPDTypeId": 2,
		"CPDTypeName": "Approved CPD Provider",
		"CourseId": 907,
		"CourseName": "61/61 Grxip: Smrss nxmprny Rxpxrpang assixs",
		"CourseDescription": "pas nxirsx wass sxxn rp ppx nirrxnp pxp pxpans fxr ppx prxprrxrs xf smrss nxmprny rnnxinps. ppx sxssaxn wass fxnis xn FRS 516, fxr smrss nxmprnaxs, rnt FRS 515 fxr manrx nxmprnaxs.\n\nnxirsx Prxgrrmmx\n\niptrpx xn xsagabasapy fxr smrss nxmprny xxxmppaxns anns",
		"Hours": 2,
		"Minutes": 0,
		"CPDYear": 2019,
		"Duration": "2h 0m",
		"Venue": "xnsanx",
		"Trainer": "Jxpn Sxswxxt",
		"Company": "61/61 Grxip",
		"IsCompleted": null,
		"WorkflowStamp": "2019-08-04T16:59:58.31",
		"CompletionDate": "2019-08-04T00:00:00",
		"IsCPDCompliant": "true",
		"LocationId": 41,
		"LocationName": "Online",
		"StartDate": "2018-03-09T00:00:00",
		"FileName": "C5BC9C43-968A-4AA7-A725-5D4796033B51.jpg",
		"ImagePath": null,
		"Email": null,
		"AttachmentName": null,
		"DeclaredDate": null,
		"CPDCompliantImage": null,
		"UserId": null,
		"RemainingDuration": null,
		"Address1": null,
		"Address2": null,
		"Address3": null,
		"Address4": null,
		"PostCode": null,
		"HostId": 31,
		"CountyName": null,
		"CountryName": null,
		"WorkflowStepId": 2,
		"CPDFormatId": 1,
		"IsDeclared": true,
		"IsLocked": false
	}
];

export default DashboardList;