define([],
    function () {
        'use strict'
        var records = [
            {
                "type": "Face to Face",
                "name": "Full Day Educational Forum - Marketing & Social Media",
                "location": "Dublin ",
                "venue": "Chartered Accountants House",
                "duration": "3.00",
                "host": "LDS",
                "trainer": "Mobile IT ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Improving Small Business Financial Management",
                "location": "Belfast",
                "venue": "The MAC, Belfast",
                "duration": "3.30",
                "host": "UDS",
                "trainer": "Ross Boyd",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Taxation of Illness Benefit, Maternity Benefit and Paternity Benefit",
                "location": "Cork",
                "venue": "The Maldron Hotel, Charville",
                "duration": "2.30",
                "host": "MDS",
                "trainer": "IPASS",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "CashFlow and Business Plan Modelling",
                "location": "Glaway",
                "venue": "The Clayton Hotel, Galway",
                "duration": "3.00",
                "host": "WDS",
                "trainer": "Friel Stafford ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Farmers Taxation Briefing",
                "location": "Glaway",
                "venue": "The Clayton Hotel, Galway",
                "duration": "3.30",
                "host": "WDS",
                "trainer": "IFAC",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "What next? Careers Advice session followed by networking opportunity ",
                "location": "Belfast",
                "venue": "The MAC, Belfast",
                "duration": "2.30",
                "host": "UDS",
                "trainer": "Acacus Recruitment",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Full Day Educational Forum - HR Update, Excel Training and The Companies Act 2014 – Practical Insights for Company Directors, Officers and Advisors",
                "location": "Cork",
                "venue": "The Maldron Hotel, Charville",
                "duration": "3.00",
                "host": "MDS",
                "trainer": "Accountable HR, Mobile IT, Creadam TECH",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "ROS",
                "location": "Dublin ",
                "venue": "Chartered Accountants House",
                "duration": "3.30",
                "host": "LDS",
                "trainer": "Ralph Smith",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Employment Law - Update",
                "location": "Glaway",
                "venue": "The Clayton Hotel, Galway",
                "duration": "2.30",
                "host": "WDS",
                "trainer": "HR specialist Evelyn Quinn ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "HR/employment law Issues",
                "location": "Belfast",
                "venue": "The MAC, Belfast",
                "duration": "3.00",
                "host": "UDS",
                "trainer": "Linzi Conway ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "HR Legal Essentials",
                "location": "Dublin ",
                "venue": "Chartered Accountants House",
                "duration": "3.30",
                "host": "LDS",
                "trainer": "IPASS",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Debit and Credit entry systems and Budget Update ",
                "location": "Glaway",
                "venue": "The Clayton Hotel, Galway",
                "duration": "2.30",
                "host": "WDS",
                "trainer": "GPA Solutions ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Conference",
                "name": "Accounting Technicians Ireland Annual Conference",
                "location": "Dublin ",
                "venue": "Chartered Accountants House",
                "duration": "6.00",
                "host": "ATI",
                "trainer": "Various",
                "description": "Accounting Technicians Ireland host the second annual conference giving members the opertunity to network with industry experts and colleagus alike while hearing about the latest innovations of the profession",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Unstructured",
                "name": "Accountancy Ireland Subscription",
                "location": "na",
                "venue": "na",
                "duration": "1.00",
                "host": "na",
                "trainer": "na",
                "description": "1 hour of self directed reading ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Unstructured",
                "name": "Inside Accountancy Subscription",
                "location": "na",
                "venue": "na",
                "duration": "1.00",
                "host": "na",
                "trainer": "na",
                "description": "1 hour of self directed reading ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "The impact of auto-enrolment",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "The future of the state pension",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "Spring Budget 2017",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "Spring Budget 2017: further analysis",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "Qualifying for entrepreneur’s tax relief",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "Self-assessment reminders",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Activity Based Management",
                "location": "na",
                "venue": "na",
                "duration": "5.00",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "It is almost a cliché to say that we are living through rapidly changing times, but it is vital that financial directors and controllers are alert to its implications.  This course takes the learner through the predominant changes in the business environment and how they have impacted management practice.  The course looks at both general management and then the control function.  It takes the learner through a range of scenarios which help them think about how they and their organisation can respond to today’s challenging environment.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Advanced Negotiation for Accountants",
                "location": "na",
                "venue": "na",
                "duration": "3.50",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "It is almost a cliché to say that we are living through rapidly changing times, but it is vital that financial directors and controllers are alert to its implications.  This course takes the learner through the predominant changes in the business environment and how they have impacted management practice.  The course looks at both general management and then the control function.  It takes the learner through a range of scenarios which help them think about how they and their organisation can respond to today’s challenging environment.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Business Performance Management",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "It is almost a cliché to say that we are living through rapidly changing times, but it is vital that financial directors and controllers are alert to its implications.  This course takes the learner through the predominant changes in the business environment and how they have impacted management practice.  The course looks at both general management and then the control function.  It takes the learner through a range of scenarios which help them think about how they and their organisation can respond to today’s challenging environment.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Coaching Skills for Accountants",
                "location": "na",
                "venue": "na",
                "duration": "5.00",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "It is almost a cliché to say that we are living through rapidly changing times, but it is vital that financial directors and controllers are alert to its implications.  This course takes the learner through the predominant changes in the business environment and how they have impacted management practice.  The course looks at both general management and then the control function.  It takes the learner through a range of scenarios which help them think about how they and their organisation can respond to today’s challenging environment.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Auditing Excel Spreadsheets",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Master Lookup Functions",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Master Date Time and Text in Excel",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Excel BI - Power Query",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Excel BI - Power View",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Master Financial Functions in Excel",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Full Day Educational Forum - Marketing & Social Media",
                "location": "Dublin ",
                "venue": "Chartered Accountants House",
                "duration": "3.00",
                "host": "LDS",
                "trainer": "Mobile IT ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Improving Small Business Financial Management",
                "location": "Belfast",
                "venue": "The MAC, Belfast",
                "duration": "3.30",
                "host": "UDS",
                "trainer": "Ross Boyd",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Taxation of Illness Benefit, Maternity Benefit and Paternity Benefit",
                "location": "Cork",
                "venue": "The Maldron Hotel, Charville",
                "duration": "2.30",
                "host": "MDS",
                "trainer": "IPASS",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "CashFlow and Business Plan Modelling",
                "location": "Glaway",
                "venue": "The Clayton Hotel, Galway",
                "duration": "3.00",
                "host": "WDS",
                "trainer": "Friel Stafford ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Farmers Taxation Briefing",
                "location": "Glaway",
                "venue": "The Clayton Hotel, Galway",
                "duration": "3.30",
                "host": "WDS",
                "trainer": "IFAC",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "What next? Careers Advice session followed by networking opportunity ",
                "location": "Belfast",
                "venue": "The MAC, Belfast",
                "duration": "2.30",
                "host": "UDS",
                "trainer": "Acacus Recruitment",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Full Day Educational Forum - HR Update, Excel Training and The Companies Act 2014 – Practical Insights for Company Directors, Officers and Advisors",
                "location": "Cork",
                "venue": "The Maldron Hotel, Charville",
                "duration": "3.00",
                "host": "MDS",
                "trainer": "Accountable HR, Mobile IT, Creadam TECH",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "ROS",
                "location": "Dublin ",
                "venue": "Chartered Accountants House",
                "duration": "3.30",
                "host": "LDS",
                "trainer": "Ralph Smith",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Employment Law - Update",
                "location": "Glaway",
                "venue": "The Clayton Hotel, Galway",
                "duration": "2.30",
                "host": "WDS",
                "trainer": "HR specialist Evelyn Quinn ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "HR/employment law Issues",
                "location": "Belfast",
                "venue": "The MAC, Belfast",
                "duration": "3.00",
                "host": "UDS",
                "trainer": "Linzi Conway ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "HR Legal Essentials",
                "location": "Dublin ",
                "venue": "Chartered Accountants House",
                "duration": "3.30",
                "host": "LDS",
                "trainer": "IPASS",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Debit and Credit entry systems and Budget Update ",
                "location": "Glaway",
                "venue": "The Clayton Hotel, Galway",
                "duration": "2.30",
                "host": "WDS",
                "trainer": "GPA Solutions ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Conference",
                "name": "Accounting Technicians Ireland Annual Conference",
                "location": "Dublin ",
                "venue": "Chartered Accountants House",
                "duration": "6.00",
                "host": "ATI",
                "trainer": "Various",
                "description": "Accounting Technicians Ireland host the second annual conference giving members the opertunity to network with industry experts and colleagus alike while hearing about the latest innovations of the profession",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Unstructured",
                "name": "Accountancy Ireland Subscription",
                "location": "na",
                "venue": "na",
                "duration": "1.00",
                "host": "na",
                "trainer": "na",
                "description": "1 hour of self directed reading ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Unstructured",
                "name": "Inside Accountancy Subscription",
                "location": "na",
                "venue": "na",
                "duration": "1.00",
                "host": "na",
                "trainer": "na",
                "description": "1 hour of self directed reading ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "The impact of auto-enrolment",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "The future of the state pension",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "Spring Budget 2017",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "Spring Budget 2017: further analysis",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "Qualifying for entrepreneur’s tax relief",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "Self-assessment reminders",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Activity Based Management",
                "location": "na",
                "venue": "na",
                "duration": "5.00",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "It is almost a cliché to say that we are living through rapidly changing times, but it is vital that financial directors and controllers are alert to its implications.  This course takes the learner through the predominant changes in the business environment and how they have impacted management practice.  The course looks at both general management and then the control function.  It takes the learner through a range of scenarios which help them think about how they and their organisation can respond to today’s challenging environment.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Advanced Negotiation for Accountants",
                "location": "na",
                "venue": "na",
                "duration": "3.50",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "It is almost a cliché to say that we are living through rapidly changing times, but it is vital that financial directors and controllers are alert to its implications.  This course takes the learner through the predominant changes in the business environment and how they have impacted management practice.  The course looks at both general management and then the control function.  It takes the learner through a range of scenarios which help them think about how they and their organisation can respond to today’s challenging environment.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Business Performance Management",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "It is almost a cliché to say that we are living through rapidly changing times, but it is vital that financial directors and controllers are alert to its implications.  This course takes the learner through the predominant changes in the business environment and how they have impacted management practice.  The course looks at both general management and then the control function.  It takes the learner through a range of scenarios which help them think about how they and their organisation can respond to today’s challenging environment.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Coaching Skills for Accountants",
                "location": "na",
                "venue": "na",
                "duration": "5.00",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "It is almost a cliché to say that we are living through rapidly changing times, but it is vital that financial directors and controllers are alert to its implications.  This course takes the learner through the predominant changes in the business environment and how they have impacted management practice.  The course looks at both general management and then the control function.  It takes the learner through a range of scenarios which help them think about how they and their organisation can respond to today’s challenging environment.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Auditing Excel Spreadsheets",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Master Lookup Functions",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Master Date Time and Text in Excel",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Excel BI - Power Query",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Excel BI - Power View",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Master Financial Functions in Excel",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Full Day Educational Forum - Marketing & Social Media",
                "location": "Dublin ",
                "venue": "Chartered Accountants House",
                "duration": "3.00",
                "host": "LDS",
                "trainer": "Mobile IT ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Improving Small Business Financial Management",
                "location": "Belfast",
                "venue": "The MAC, Belfast",
                "duration": "3.30",
                "host": "UDS",
                "trainer": "Ross Boyd",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Taxation of Illness Benefit, Maternity Benefit and Paternity Benefit",
                "location": "Cork",
                "venue": "The Maldron Hotel, Charville",
                "duration": "2.30",
                "host": "MDS",
                "trainer": "IPASS",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "CashFlow and Business Plan Modelling",
                "location": "Glaway",
                "venue": "The Clayton Hotel, Galway",
                "duration": "3.00",
                "host": "WDS",
                "trainer": "Friel Stafford ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Farmers Taxation Briefing",
                "location": "Glaway",
                "venue": "The Clayton Hotel, Galway",
                "duration": "3.30",
                "host": "WDS",
                "trainer": "IFAC",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "What next? Careers Advice session followed by networking opportunity ",
                "location": "Belfast",
                "venue": "The MAC, Belfast",
                "duration": "2.30",
                "host": "UDS",
                "trainer": "Acacus Recruitment",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Full Day Educational Forum - HR Update, Excel Training and The Companies Act 2014 – Practical Insights for Company Directors, Officers and Advisors",
                "location": "Cork",
                "venue": "The Maldron Hotel, Charville",
                "duration": "3.00",
                "host": "MDS",
                "trainer": "Accountable HR, Mobile IT, Creadam TECH",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "ROS",
                "location": "Dublin ",
                "venue": "Chartered Accountants House",
                "duration": "3.30",
                "host": "LDS",
                "trainer": "Ralph Smith",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Employment Law - Update",
                "location": "Glaway",
                "venue": "The Clayton Hotel, Galway",
                "duration": "2.30",
                "host": "WDS",
                "trainer": "HR specialist Evelyn Quinn ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "HR/employment law Issues",
                "location": "Belfast",
                "venue": "The MAC, Belfast",
                "duration": "3.00",
                "host": "UDS",
                "trainer": "Linzi Conway ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "HR Legal Essentials",
                "location": "Dublin ",
                "venue": "Chartered Accountants House",
                "duration": "3.30",
                "host": "LDS",
                "trainer": "IPASS",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Face to Face",
                "name": "Debit and Credit entry systems and Budget Update ",
                "location": "Glaway",
                "venue": "The Clayton Hotel, Galway",
                "duration": "2.30",
                "host": "WDS",
                "trainer": "GPA Solutions ",
                "description": "Join the LDS For a full day educational forum covering various topics including Understand your responsibilities as an employer for the taxation of Illness Benefit and Occupational Injury Benefit paid to your employees by the DSP\nLearn how Revenue deals with the taxation of Maternity Benefit, Adoptive Benefit, Health & Safety Benefit and Paternity Benefit and how this impacts on payroll\nUnderstand how a record of sick days for HR purposes differs from a record of Illness Benefit received from the DSP",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Conference",
                "name": "Accounting Technicians Ireland Annual Conference",
                "location": "Dublin ",
                "venue": "Chartered Accountants House",
                "duration": "6.00",
                "host": "ATI",
                "trainer": "Various",
                "description": "Accounting Technicians Ireland host the second annual conference giving members the opertunity to network with industry experts and colleagus alike while hearing about the latest innovations of the profession",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Unstructured",
                "name": "Accountancy Ireland Subscription",
                "location": "na",
                "venue": "na",
                "duration": "1.00",
                "host": "na",
                "trainer": "na",
                "description": "1 hour of self directed reading ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Unstructured",
                "name": "Inside Accountancy Subscription",
                "location": "na",
                "venue": "na",
                "duration": "1.00",
                "host": "na",
                "trainer": "na",
                "description": "1 hour of self directed reading ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "The impact of auto-enrolment",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "The future of the state pension",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "Spring Budget 2017",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "Spring Budget 2017: further analysis",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "Qualifying for entrepreneur’s tax relief",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "CPD Bite",
                "name": "Self-assessment reminders",
                "location": "na",
                "venue": "na",
                "duration": "0.15",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "Useful KPIs rely on being able to record the right data efficiently. This bite looks at the type of data you need to collect, along with tips on how best to collect it.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Activity Based Management",
                "location": "na",
                "venue": "na",
                "duration": "5.00",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "It is almost a cliché to say that we are living through rapidly changing times, but it is vital that financial directors and controllers are alert to its implications.  This course takes the learner through the predominant changes in the business environment and how they have impacted management practice.  The course looks at both general management and then the control function.  It takes the learner through a range of scenarios which help them think about how they and their organisation can respond to today’s challenging environment.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Advanced Negotiation for Accountants",
                "location": "na",
                "venue": "na",
                "duration": "3.50",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "It is almost a cliché to say that we are living through rapidly changing times, but it is vital that financial directors and controllers are alert to its implications.  This course takes the learner through the predominant changes in the business environment and how they have impacted management practice.  The course looks at both general management and then the control function.  It takes the learner through a range of scenarios which help them think about how they and their organisation can respond to today’s challenging environment.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Business Performance Management",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "It is almost a cliché to say that we are living through rapidly changing times, but it is vital that financial directors and controllers are alert to its implications.  This course takes the learner through the predominant changes in the business environment and how they have impacted management practice.  The course looks at both general management and then the control function.  It takes the learner through a range of scenarios which help them think about how they and their organisation can respond to today’s challenging environment.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Coaching Skills for Accountants",
                "location": "na",
                "venue": "na",
                "duration": "5.00",
                "host": "Nelson Croom",
                "trainer": "na",
                "description": "It is almost a cliché to say that we are living through rapidly changing times, but it is vital that financial directors and controllers are alert to its implications.  This course takes the learner through the predominant changes in the business environment and how they have impacted management practice.  The course looks at both general management and then the control function.  It takes the learner through a range of scenarios which help them think about how they and their organisation can respond to today’s challenging environment.",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Auditing Excel Spreadsheets",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Master Lookup Functions",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Master Date Time and Text in Excel",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Excel BI - Power Query",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Excel BI - Power View",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            },
            {
                "type": "Online",
                "name": "Master Financial Functions in Excel",
                "location": "na",
                "venue": "na",
                "duration": "2.00",
                "host": "The Excel Club",
                "trainer": "na",
                "description": "The Excel Club is an online Microsoft Excel Course, written by an Accountant, focusing on intermediate to expert Excel.  \n\nThe course is focused on Functions and Formula and a working knowledge of Excel is required. This course has been designed for Accounting and Finance professionals who what to develop their MS Excel skill far beyond a basic level.  ",
                "coursedate": "21-07-2017"
            }
        ]

        return Object.freeze(records);
    });